### ISSUE TITLE
Banners can appear misaligned on certain zoom options

### ISSUE THREAD

**Issue by Garfieldwxg55** [felixkmh/ThemeExtras-for-Playnite#10]
Hi, I've been using this plugin for awhile to display banners which corelate to the specific platforms/game stores that each game belongs to. However, recently, I changed the size of my game covers in Grid Mode, and this seems to have caused a problem where the banners seem to be misaligned, appearing slightly smaller than the actual games. Further, when the game is hovered over with the cursor, the banner can moving slightly, displaying a visible gap between the game and banner.

Banners are one of my favorite parts of Playnite, and I would love to see this issue fixed!

**Comment by felixkmh** [comment]
I don't think that that's something I can fix in ThemeExtras. The theme you are using controls how the banners are displayed, ThemeExtras just provides the image. So you should bring this issue to your themes devs attention.

**Comment by Garfieldwxg55** [comment]
Huh, ok, sorry for opening the bug report here, thanks for your help, I'll see if I can contact them!
