### ISSUE TITLE
Option to base banner choice on source

### ISSUE THREAD

**Issue by WowIMadeThis** [felixkmh/ThemeExtras-for-Playnite#4]
Would it be possible to add an option to base choice of banner on Source instead of Library or Platform?

It's not possible to change library for games that are imported manually, which means I'm not able to change the banner of manually imported games that are available from EA through Gamepass. (Those games can't be imported automatically.)

Currently the only banner these games get is the PC games banner, but I would like to change them to the Origin banner.

**Comment by felixkmh** [comment]
Assigning banners based on source names is already supported. But themes need to be configured for that, see [wiki](https://github.com/felixkmh/ThemeExtras-for-Playnite/wiki/Configuration).
You can of course modify the config file yourself and add a new folder with banners named like the sources.
If you want to be able to set theme independent default banners within ThemeExtras, you can open a separate issue.
