### ISSUE TITLE
Theme Banners Supersede Override Banners

### ISSUE THREAD

**Issue by SkyNinja** [felixkmh/ThemeExtras-for-Playnite#5]
If theme banners and override banners have a conflict, theme banners seem to win. Based on the name, I would expect banner overrides to win such conflicts.

![2023-01-13](https://user-images.githubusercontent.com/4765557/212441799-78fec5da-b72e-4269-ac84-f49349a5351b.png)

**Comment by felixkmh** [comment]
I reversed the order of evaluation by accident. Should be fixed in v1.4.2
