### ISSUE TITLE
Banner display is repeatedly faulty in both view modes if banner overrides are used

### ISSUE THREAD

**Issue by CanRanBan** [felixkmh/ThemeExtras-for-Playnite#7]
Details view: Switching with arrow keys doesn't update the banner in all cases.
Grid view: Some games display a banner which should only be displayed for games more than 1 spot away.

To reproduce the issue:
- At least 4 games are necessary:
- Game 1: Library `A`, Source `A*`, Platform `PC`
- Game 2: Library `Playnite`, Source `B`, Platform `PC`
- Game 3: Library `Playnite`, Source `C`, Platform `PC`
- Game 4: Library `D`, Source `D`, Platform `PC`
- Additionally other games to be able to scroll and one of these games uses Source `E`.

- No source banner override set for: `A*`, `D`
- Source banner overrides set for: `B`, `C`, `E`
- No other banner overrides than these 3 set.
- Grid view: 4 games are displayed in each row.

Note: A = A* with different capitalization (I guess it doesn't affect it but in my opinion it's better to state all details).

Confirmed this issue for two themes: `DH_Dawn`, `Harmony`
Confirmed this issue for Theme Extras versions: 1.4.1 and 1.4.2

Details view:
If I use arrow keys to switch between these four games the two games being part of Playnite library always display the same banner.
If I cycle from top to bottom game 2 and 3 display the banner of game 2.
If I cycle from bottom to top game 3 and 2 display the banner of game 3.
Game 1 and 4 display their library banner without issues.

Grid view:
If the games are in view when switching to grid view the banners are displayed properly.
If the games are not in view (either because of selecting a game far away or because of scrolling to a different game and scrolling back) the banner display is faulty in some cases. It doesn't matter if arrow keys or mouse scrolling is used. It also doesn't matter how fast I'm scrolling. One of the two `Playnite` library games in between the two other libraries will sometimes display a banner which doesn't belong to itself or any of it's direct neighbors. It's similar to the details view issue but the distance between the game with the faulty banner and the next game with said banner is bigger.

**Comment by felixkmh** [comment]
Fixed via 8f3e24a8b1238f3fe8adbd1457313845c41e5c49
